### ISSUE TITLE
Totally noob question: How to embed this SwiftOSC

### ISSUE THREAD

**Issue by enzyme69** [devinroth/SwiftOSC#11]
I am stuck in actually embedding the SwiftOSC into my iOS project. I copy the whole folder of compiled SwiftOSC, and do an import, but nothing.... No such module 'SwiftOSC'

Tested using this method to import framework, but does not work.
https://stackoverflow.com/questions/3352664/how-to-add-existing-frameworks-in-xcode-4

So we need client and server, my idea is to use the Face AR (iPhone X) to send OSC message from the iPhone into the Mac. Similar to TouchOSC, but actually using Face Camera and tracking my head and facial expression. Maybe the iPhone become a server or client?

Any possible example template? 

Thanks beforehand.

**Comment by devinroth** [comment]
1. Create a new project and link the framework. 
<img width="640" alt="screen shot 2017-10-01 at 11 37 05 pm" src="https://user-images.githubusercontent.com/13010961/32457355-b21b38ac-c2dd-11e7-8969-7e0010937963.png">
![screen shot 2017-10-01 at 11 37 33 pm](https://user-images.githubusercontent.com/13010961/32457363-b8cfa750-c2dd-11e7-991b-a6577ea3fdf2.png)
![screen shot 2017-10-01 at 11 37 43 pm](https://user-images.githubusercontent.com/13010961/32457367-baec4d18-c2dd-11e7-8eed-8a7553fb5c7c.png)
Looks like you need to link twice. The first time imports the files and the 2nd time links the framework. No idea why you need to do it twice. Probably missing something simple but that’s what you need to do.

Some test code to make sure things are running. 
<img width="640" alt="screen shot 2017-10-01 at 11 38 33 pm" src="https://user-images.githubusercontent.com/13010961/32457374-c73791e0-c2dd-11e7-9bb7-006d8a512d38.png">

If everything works properly and you have OSC Monitor open from my macOS examples you should see this.

![screen shot 2017-10-01 at 11 39 40 pm](https://user-images.githubusercontent.com/13010961/32457391-d6da8ae4-c2dd-11e7-868c-ae528cd9917f.png)

Make sure you build the Framework first before building the project.

**Comment by devinroth** [comment]
I think I missed a step. Make sure you imbed the framework. I'm uploading a demo iOS app for you to look at.

**Comment by enzyme69** [comment]
Thanks Devin, I will follow the step by step and see how it goes. Will update..

**Comment by enzyme69** [comment]
When I looked around, I thought what I need to do was to compile the framework first, and then copy paste the .framework into my project... this still not working.
![screen shot 2017-11-11 at 14 43 51](https://user-images.githubusercontent.com/3952687/32685888-c42e9f4c-c6ee-11e7-9354-ef143b5bd3df.png)

Following your steps now....

**Comment by devinroth** [comment]
You can do it that way. You have to imbed the binary though. Check out the iOS test app I just added. 

Devin Roth

**Comment by enzyme69** [comment]
I changed the name of that project file from "SwiftOSC for iOS.xcodeproj" into "SwiftOSCforiOS.xcodeproj" and did the linking following your steps.

Module not found error is gone, but I am getting new strange error and the app crashes:

![screen shot 2017-11-11 at 15 17 38](https://user-images.githubusercontent.com/3952687/32686117-7d746aaa-c6f3-11e7-9fc1-0a55a2c09960.png)

**Comment by enzyme69** [comment]
Embedding binary step is not clear still. Investigating .... wonder what that "image not found" means.

**Comment by devinroth** [comment]
The image not found is because the binary was imbedded. Found in the targets/general tab.    I'll send an image when I have a chance. 

Devin Roth

**Comment by enzyme69** [comment]
Thanks Devin looking forward to this. If it works, I will make tutorial about it from scratch. This embed thing is supposedly simple.

**Comment by devinroth** [comment]
Once I get cocoapods up and running it will make this a lot easier. 

Devin Roth

**Comment by enzyme69** [comment]
I dragged the framework into "Embedded Binaries" under General and seems to do the work.

![screen shot 2017-11-11 at 15 56 53](https://user-images.githubusercontent.com/3952687/32686435-fbab1bb2-c6f8-11e7-9789-f0df7615e3fc.png)

Thanks for your help, I will do some test. The idea is to get the Face AR  or AR tracking to send OSC message.
