### ISSUE TITLE
XCODE 9.1

### ISSUE THREAD

**Issue by 5opr4ni** [devinroth/SwiftOSC#14]
Hi

Having some issues with the main workspace in Xcode 9.1
The frameworks won't build out of that.

Did work in 9.0

/olle

**Comment by 5opr4ni** [comment]
<Group
      location = "group:Framework"
      name = "Framework">
      <FileRef
         location = "group:/Users/devin/Dropbox/Devin/Code/Xcode/SwiftOSC/Framework/macOS/macOS.xcodeproj">
      </FileRef>
      <FileRef
         location = "group:/Users/devin/Dropbox/Devin/Code/Xcode/SwiftOSC/Framework/iOS/iOS.xcodeproj">
      </FileRef>
   </Group>

**Comment by 5opr4ni** [comment]
`<Group
      location = "group:Framework"
      name = "Framework">
      <FileRef
         location = "group:/Users/devin/Dropbox/Devin/Code/Xcode/SwiftOSC/Framework/macOS/macOS.xcodeproj">
      </FileRef>
      <FileRef
         location = "group:/Users/devin/Dropbox/Devin/Code/Xcode/SwiftOSC/Framework/iOS/iOS.xcodeproj">
      </FileRef>
   </Group>`

**Comment by devinroth** [comment]
That bizarre. Let me see what I can do.

**Comment by 5opr4ni** [comment]
Hi, grate project btw.

There is two issues here, frameworks don't show up as build targets in the workspace, and the workspace has hardcoded paths.

/olle

**Comment by devinroth** [comment]
The two issues were related. 

Try now.

**Comment by 5opr4ni** [comment]
Grate!
