### ISSUE TITLE
Pod recipie don't work

### ISSUE THREAD

**Issue by 5opr4ni** [devinroth/SwiftOSC#18]
Hi

Sorry to say, your Pod script don't do the work.

/olle

**Comment by devinroth** [comment]
Did you include the “use_frameworks!” In your podfile?

**Comment by 5opr4ni** [comment]
Yes!

**Comment by devinroth** [comment]
What errors are you getting?  Or did you figure it out.

**Comment by BildPeter** [comment]
I also can't get it to work:
'No such module 'SwiftOSC''
Tried the solutions from here till now, which didn't work:
https://stackoverflow.com/questions/31065447/no-such-module-when-i-use-cocoapods

**Comment by devinroth** [comment]
Here's my podfile and it work fine. Maybe you're missing the platform?

```
platform :ios, '9.0'

target 'PodTest' do
    use_frameworks!
    pod 'SwiftOSC', '~> 1.1'

end
```

**Comment by BildPeter** [comment]
It didn't work. The other way (download, compiling and embedding) resolves the issue, but then neither server, nor client work...

That's my file

`platform :ios, '11.0'

target 'DeleteMe' do
    use_frameworks!
    pod 'SwiftOSC', '~> 1.1'

end
`

With iOS 9 it didn't work at all!
I am using xCode9 with macOS10.13.1

**Comment by devinroth** [comment]
In the meantime try
```
pod 'SwiftOSC', :git => "https://github.com/devinroth/SwiftOSC.git"
```

**Comment by devinroth** [comment]
And make sure you compile the framework first before using import SwiftOSC.

**Comment by devinroth** [comment]
Hey have you tried pod update?

**Comment by BildPeter** [comment]
The line with 
pod 'SwiftOSC', :git => "https://github.com/devinroth/SwiftOSC.git"
actually worked! Thank you!

**Comment by devinroth** [comment]
Have you tried the normal method? I'm pretty sure it's fixed but I just want confirmation.
