### ISSUE TITLE
Help please... simulator works great, won't build for Device

### ISSUE THREAD

**Issue by mrmacmusic** [devinroth/SwiftOSC#20]
I'm new to Xcode but was really pleased to have been able to create an app using the SwiftOSC framework that works perfectly when targeting the Simulator, however when I try and build to test on my tethered iPhone I get build errors (e.g. "Use of unresolved identifiers")..?

I know I must be doing something silly so sorry for the newbie question, but hopefully someone can point me in the right direction to get this working!?

**Comment by devinroth** [comment]
That’s not enough info for me to help you. What specifically does it say? The more info the better.

**Comment by mrmacmusic** [comment]
Oh, thanks for responding so promptly Devin!

OK... when I change the target from any of the iOS Simulators to "iPhone" (or indeed the 'Generic iOS Device' option) I get 84 red exclamation marks, all under "Swift Compiler Error" starting as follows:
'address_makelive' used within its own type
Could not infer type for 'address_makelive'
Use of unresolved identifier 'OSCAddressPattern'
etc..etc.. 

As soon as I change the target back to one of the simulators, the red exclamation marks disappear and I can run my app in the simulator.

**Comment by devinroth** [comment]
I’m guessing it’s a linking issue. Are you using CocoaPods or manually adding the framework?

If the latter you need to make sure the framework is embedded otherwise it won’t work. Try that first.

**Comment by mrmacmusic** [comment]
Manually Devin, and I thought I had embedded the framework: it shows up in both the "Embedded Binaries" and "Linked Frameworks and Libraries" section of my apps General Settings. 

I've been scratching my head trying to figure out what I'm doing wrong, but presumably I have embedded the Framework correctly otherwise the app wouldn't work in the simulator (or is that not the case?!)...

Sorry, I realise this is a newbie install type issue but really appreciate your assistance!

**Comment by devinroth** [comment]
The framework is stored on the computer so it doesn’t need to be embedded to run in the Simulator. 

Try creating a new project. Build and embed the framework and add some simple code like var client = OSCClient(). See if you can get that running on your phone first. I really think the embedding is the problem but if not this will rule it out.

**Comment by mrmacmusic** [comment]
Thanks Devin – will try starting from scratch... can I just check the following process is correct in case I've missed a key step? 

1. Open SwiftOSC-Master
2. Build Framework (for iOS)
3. Reference this Framework (from the Finder) in the General Settings for my app, so that it appears under both "Embedded Libraries" and "Linked Frameworks and Libraries" 

Are there any settings I should check before building the framework in step 2, and indeed a specific way I should go about step 3..? I'm concerned I'm perhaps not even doing that right!

Googling suggests that I might need to create a "Fat" framework that will work for both Simulator and Device, but I don't know if that is relevant or out of date..?

**Comment by mrmacmusic** [comment]
I think I'm making progress Devin, but still not confident I'm going about this the correct way?

I tried starting again and did the following:

1. Built separate SwiftOSC frameworks from your SwiftOSC-Master project, one using "Generic iOS Device" as the target, and another using one of the Simulators.
2. Once successfully built, I copied these frameworks out of their respective Xcode/DerivedData folders to a new directory on my Mac, into two new folders – 'device' and 'simulator' – so I can use these in my app
3. To embed one of these frameworks in my app I dragged it into the app Project panel (choosing to "copy" files) and then in the general settings clicked the "+" sign under 'Embed Binaries' to select it...
4. To test, I added "import SwiftOSC" and a few other lines of code (e.g. var client = OSCClient()

What I've found is:

if at step 3 above I drag in and embed the 'device' Framework, then choose 'iPhone' (or 'Generic iOS Device') as the target, build and run works but I get errors if I choose any of the simulators as the target; and vice-versa e.g.
if I drag/copy and embed the 'simulator' Framework, then choose any simulator as the target, build and run works but I get errors if I choose 'iPhone' as my target

In both cases the red exclamation marks appear and I get Swift Compiler Errors including:
'client' used within its own type
Could not infer type for 'client'

I suppose I've got a working solution as I can copy either the device or simulator framework, but I can't help feeling I'm doing something wrong, or must be missing something?? Sorry, as per the first post I'm a bit new to this and appreciate being pointed in the right direction!

**Comment by devinroth** [comment]
Does the demo app work fine for you?

**Comment by devinroth** [comment]
No problems on this end. Maybe I wasn’t specific enough with my suggested code. 

import SwiftOSC

var client = OSCClient(address: "", port: 2020)


I placed this in the top level of the app delegate. 

Just set it up and ran it on my iPhone with no problems. 

You can send me your project and I can see what you’re doing wrong.

**Comment by mrmacmusic** [comment]
Sorry Devin, but I've been offline for the last week...

You were specific enough with the code thanks and this is what I tried from scratch (I had simplified the code when step 4 above)

FYI I have different problems trying to run the demo app – it works fine in the Simulator but won't build to my tethered iPhone because of 'Code Signing Errors' – but I'm not too phased by that, more I'd like to understand why I have to use 2 different builds of the SwiftOSC.framework, but I'll persevere here swapping the simulator and device frameworks as required for now :)

**Comment by devinroth** [comment]
I'm not entirely sure. I have no such issues on my end. You shouldn't need multiple builds of the framework. Perhaps some xcode setting you have different? Anyway I suggest getting that demo up and running and seeing how that works and we'll go from there.

**Comment by mrmacmusic** [comment]
Thanks Devin. Yes, I suspect that as an Xcode newbie I very possibly have some key settings wrong re deployment/build etc.etc.. Lots of gaps in my knowledge to fill but unfortunately because I need to dip in and out of 'developer mode' am not getting a chance to fully engage my brain here as much as I'd like and I'm probably trying to run before I can walk too...

Really appreciate your help and am glad that I found SwiftOSC framework as it has allowed me to build an app with the functionality I need.

**Comment by devinroth** [comment]
You’re welcome.

Just a thought. Why not try giving cocoapods a try? It sets the framework up for you automatically. There are plenty of tutorials online.
