### ISSUE TITLE
Carthage compatibility

### ISSUE THREAD

**Issue by rukano** [devinroth/SwiftOSC#21]
Hi, are there any plans to support Carthage for building and including SwiftOSC as a framework in a project? Would be nice! :)

**Comment by rukano** [comment]
Hi, yes, they work good together. I use pods in many projects, and in many other Carthage if I can. actually just the build scheme has to be shared for carthage to build the .framework. That's all. :)

**Comment by rukano** [comment]
That's it. I've been using carthage on my fork, that's why I did the pull request. :) It's that easy. :D

**Comment by devinroth** [comment]
Awesome. Thanks for setting that up. 

Devin
