### ISSUE TITLE
Port issue

### ISSUE THREAD

**Issue by arthas994** [devinroth/SwiftOSC#23]
Hi, trying to use this framework but I've some problems with server ports..
Defining a port and even by printing i got that port, but on local i got another port.
Tried to send message to the port i specified and does not work, on the other local port works.. Any help? Thank you!
<img width="1287" alt="screen shot 2018-07-23 at 12 58 45" src="https://user-images.githubusercontent.com/23313649/43073045-7e9c4e50-8e78-11e8-82ce-fa9be88d7d7b.png">

**Comment by arthas994** [comment]
PS: If send message to the "other" port I receive message

**Comment by devinroth** [comment]
I’m not a networking expert and borrowed the UDP code. 

Does it work with the port I have in my demo? There might be a bug somewhere.

**Comment by devinroth** [comment]
Closing. Reopen if you're still having issues.
