### ISSUE TITLE
How to receive message as OSC Server

### ISSUE THREAD

**Issue by parul1986** [devinroth/SwiftOSC#25]
Hi

I used OSC Client and it is working great. Now I am trying use my app as OSC Server to receive messages. But when I am sending message nothing gets received. Please help.
I am using the following code 

**declaration and initialization**
var server = OSCServer(address: "127.0.0.1", port: 9000)

**in viewdidload**
server.start()
server.delegate =  OSCHandler()

**Another class**
class OSCHandler: OSCServerDelegate {
    func didReceive(_ message: OSCMessage){
        print(message)
    }
}

**Comment by devinroth** [comment]
Try leaving the server address blank.

**Comment by parul1986** [comment]
Yup, got it ... works :)
