### ISSUE TITLE
OSC Server

### ISSUE THREAD

**Issue by ADE222070** [devinroth/SwiftOSC#26]
Hi there, I have got the OSC client working within my app but I also need the server. I have tried getting my head around it but attempt have been unsuccessful.

Would you consider making an example iOS app for the server just like you have for the client?

Thanks

**Comment by devinroth** [comment]
In the meantime it works exactly like the macOS example or the Playground. You can copy that code. The key thing everyone gets wrong is the server IP address needs to be blank. It doesn’t do what you think it does.

**Comment by James2804** [comment]
i cant seem to get it working either tried everything I can think of but still been unsuccessful, maybe an example for the server would be great and much appreciated.

**Comment by devinroth** [comment]
Post your code and I can help you.

**Comment by ADE222070** [comment]
To be honest I don't really have anything to post. I get more errors than anything. I am using a bridge with the following code:
```swift  
func sendOSC() {
     let message = OSCMessage(address1, 1.0)
     client.send(message)
}
```
and then the following to trigger it.
```swift        
self.wkWebView?.bridge.register({ (parameters, completion) in
     ViewControllerOSC().sendOSC()
 }, for: "SendOSC")
```

What I now need to do is use the server to receive a predefined value and then trigger the bridge to send the value to the web server using javascript. I would also like the server to be always on.

Does this make sense?

**Comment by devinroth** [comment]
I’m not super familiar with JavaScript so I can’t help you with that. 

What errors are you getting?

**Comment by ADE222070** [comment]
Okay so I am making progress. I started a new project and got everything working. I have now added it into my existing project but I'm not even getting the messages appear on the console. Would you please mind taking a look? I have added you to a team that includes the repo, you can find it [here](https://github.com/Research-Production-Park/Immersive-Classroom-IOS/tree/Alpha-OSCServer).

Your help would be very much appreciated.
