### ISSUE TITLE
 Module issue in Playground code

### ISSUE THREAD

**Issue by narner** [devinroth/SwiftOSC#27]
Hey mate, great project! Working on integrating it into a few apps at the moment. 

Noticed one issue; when opening up the workspace and attempting to run the playground, I'm getting this:

```
error: could not build Objective-C module 'SwiftOSC'
```

**Comment by devinroth** [comment]
Did you already build the framework with no issues?

Also what version of Xcode/OS are you using?

**Comment by narner** [comment]
Yeah, built the framework without any problem. 
I'm on Xcode 10 / macOS 10.14.1 

(Had another question as well; but that may be related to something else - will make another issue shortly).

**Comment by devinroth** [comment]
Okay. I’ll check it out on my other system tomorrow and let you know.

I’m running an older version of Xcode and I think it makes a difference.

**Comment by devinroth** [comment]
Works fine for me on Xcode 10/ macOS 10.14. The only other thing I can think of is that the Playground is using the macOS version of the framework. Try building that and seeing if it runs.

That being said, playground support has been shoddy at best. If you can’t get that running you’re really not missing anything. 

Are the test apps working fine?

**Comment by narner** [comment]
Yup, rebuilding made everything work fine - closing!
