### ISSUE TITLE
Problem with sending client data from a physical device 

### ISSUE THREAD

**Issue by narner** [devinroth/SwiftOSC#28]
Hey Devin, 

One other question for you - the context I'm working in has a macOS app that will act as a server, and an iOS app that will act as a client. 

In the mac app, I have the following code for creating an OSC server:

```
server = OSCServer(address: "", port: 8080)
server.delegate = self
server.start()
```

And implemented the delegate method for receiving OSC messages:

```
    func didReceive(_ message: OSCMessage) {
        
        receivedMessage = message
        
        print(receivedMessage)
   }
```

On the iOS side, I have the following code for setting up an OSC client:

```
client = OSCClient(address: "localhost", port: 8080)
let message = OSCMessage("some message")
client.send(message)
```

However, for whatever reason; that delegate method is not being called at all when I'm sending information from the iOS app to the macOS app.

I also tried replacing the client's `address` variable with the IP address of the iPhone, but that didn't work either. 

Anything I'm missing?

**EDIT** I fixed part of the problem as far as the delegate method (a simple mistake on my end); so I'm now able to send receive messages on my mac app from an iOS client. 

*However*, for whatever reason; I'm not able to do that when running the iOS app on a physical device.

**Comment by narner** [comment]
Also, the iOS version I'm running is 12.0.1

**Comment by devinroth** [comment]
For the client you need to put in the IP address of where you’re sending. By using localhost or the iPhone’s IP address it’s sending the data to itself. Put in the IP address of the Mac and it should be working correctly.

**Comment by narner** [comment]
Oh gotchya; yeah that was silly!

Ok, I tried setting the client (iPhone)'s IP address to be that of the Mac I'm trying to send too: 

```
    var ipAddress:String = "216.38.155.180"
    var port:Int = 8080
```

However, still having the same issue where the `didReceive` delegate function isn't getting called for some reason.

**Comment by narner** [comment]
Ahh - I figured it out (not a framework issue but something else)...I had been trying to use the IP address from typing "what's my IP address" into Chrome. 

However, it worked great when actually using the IP gotten from looking at the Systems Preferences.

**Comment by devinroth** [comment]
Yup that would do it. Glad you figured it out.
