### ISSUE TITLE
removing "/" safeguards from OSCAddressPattern

### ISSUE THREAD

**Issue by JCurtisRMIT** [devinroth/SwiftOSC#29]
Hi Devin,

New to Swift, but loving SwiftOSC. 

I've got an OSC server inside an app that is already written to parse specific OSC Address paths that don't include the opening "/" character. 

I can send messages using other OSC frameworks (oscP5, ofxOSC, MaxMSP etc) without the opening slash - and the server successfully parses these messages. Rebuilding this server from source and altering the parser isn't feasible. 

I'd like to be able to use SwiftOSC, but can't seem to successfully send any messages after changing the OSCAddressPattern to remove the opening slash "/"

Having a dig through OSCAddressPattern.swift I think I can see that it's probably returning false when the opening slash is removed. Can this be overridden safely?

Commenting out this feels hacky.. but works.

`     
        if address.first != "/" {
            return false
        }`

**Comment by JCurtisRMIT** [comment]
Actually, commenting out these lines only worked in the OSCTest example.

In the project I'm using where SwiftOSC was installed via CocoaPods, commenting out these lines doesn't work.

Is there an easy fix?

**Comment by devinroth** [comment]
Sorry wrong button.

**Comment by devinroth** [comment]
It will be safer if you change to the following. 
```
if address.first != "/" {
    self.string = "/" + address
}
```
Haven't tested but it should work. The will not work without the leading "/" so this way you make it optional to add and add it if it doesn't exist.

**Comment by JCurtisRMIT** [comment]
Hi Devin,

Thanks for the speedy response. 

Rebuilding the framework didn't work for the Cocoapods import and threw an error re: editing privileges. 

I've tested OSC frameworks (oscP5 (processing), ofxOSC (openFrameworks), MaxMSP) and none of these are prepending their OSC messages with a leading slash.

Would a rebuild for cocoapods making your leading slash be optional be possible?

Would help people make SwiftOSC clients that can actually communicate with servers using the standard in the above frameworks and where rebuilding OSC server sources isn't possible

**Comment by JCurtisRMIT** [comment]
The lines you provided above force the slash - which doesn't fix the issue when server parsers aren't written to expect it

**Comment by JCurtisRMIT** [comment]
For context:

How oscP5 servers handle addresspatterns without opening slashes from clients:

<img width="700" alt="screen shot 2018-11-23 at 12 46 41 pm" src="https://user-images.githubusercontent.com/25715542/48926201-049a1980-ef20-11e8-90ba-96631ca47e06.png">


How SwiftOSC servers handle addresspatterns without opening slashes from clients:

<img width="478" alt="screen shot 2018-11-23 at 12 50 55 pm" src="https://user-images.githubusercontent.com/25715542/48926231-2c897d00-ef20-11e8-8860-009e99e442b1.png">

**Comment by devinroth** [comment]
I’m following exactly what in the OSC spec. 

"An OSC Address Pattern is an OSC-string beginning with the character '/' (forward slash).”
http://opensoundcontrol.org/spec-1_0 <http://opensoundcontrol.org/spec-1_0>

The implementation in oscP5 (processing), ofxOSC (openFrameworks), MaxMSP is invalid according to the spec which is why they show up as invalid. I wouldn’t be surprised if all of those programs use the same open source framework that allows the invalid addresses. 

Feel free to change the code to fit your needs but I will have to do some research and give it more consideration before I make it a permanent change. Playing well with others is important despite the spec. Maybe the solution is to accept the values but give a warning. To properly implement it will take me time. 

For a quick fix for you just download the source and compile the framework yourself.

**Comment by JCurtisRMIT** [comment]
Thanks Devin, I think you are probably right here - they all could be using the same base framework which is ignoring that spec

Requesting you pivot your code around this is probably a bit too preemptive - sorry for that!  Mind if I fork it instead?

Btw really enjoyed the generative swift midi stuff!

Cheers :)
J

**Comment by devinroth** [comment]
Please fork. And like I said I will consider making a change. 

Thanks for bringing this to my attention.

**Comment by JCurtisRMIT** [comment]
Thanks Devin - after doing some digging around here I found this. Lots of great thoughts about this same issue. I think you are spot on about being built on the same framework (oscpack perhaps) 

https://github.com/colinbdclark/osc.js/issues/72

It feels like somewhere a decision was made to support using plain strings and ints as addresspatterns for use with supercollider. 

Adhering to the protocol seems like a good idea though! 

Mind if I fork SwiftOSC?

Btw, really enjoyed your generative midi pieces - cool stuff :D

**Comment by devinroth** [comment]
Thanks. That was a good read. I think I agree with @colinbdclark on this. Best of luck with your app.
