### ISSUE TITLE
Cannot broadcast messages

### ISSUE THREAD

**Issue by 0x0c** [devinroth/SwiftOSC#32]
Hello, I use SwiftOSC to broadcast messages, but I cannot receive my computer.
The computer and my iPhone connects same wifi.
Sending messages to specific ip address is works.

Is there any workaround?

**Comment by devinroth** [comment]
I’m sorry I don’t quite understand. Could you be more specific?

**Comment by 0x0c** [comment]
The computer and the iPhone joined same network.
Its network address is `192.168.1.0`, and my app runs on the iPhone send messages to `192.168.1.255` as known as broadcast address.
I think my computer receive messages, however no messages received.
Instead of broadcasting, send specific address like `192.168.1.100` which is the computer's address, it works.

I found `public func enableBroadcast()` in UDPClient and I edit `var client: UDPClient` to `public ` in `OSCClient.swift` at line 16.
Then, call `func enableBroadcast()` before call `public func send(_ element: OSCElement)` in `OSCClient`, it works.

Sorry for my broken English :(
Regards

**Comment by 0x0c** [comment]
I describe a detail of my workaround below.

First, in `OSCClient.swift`, I change like this

![screen shot 2019-02-17 at 2 34 32](https://user-images.githubusercontent.com/154327/52903109-9209b300-325c-11e9-9a55-ac01ee6d3c1f.png)

then, send message like this

```
let client = OSCClient(address: ipAddress, port: port)
client.client.enableBroadcast()
client.send(OSCMessage(...))
```

**Comment by devinroth** [comment]
So is it working now?

The UDP socket code that I’m using is not my own so it’s really hard for me to know exactly what the problem is. I’m working on a new version using Apple’s Network framework but I don’t know if broadcast is supported. 

What you can do is swap out the socket code in SwiftOSC with something else you’re more familiar with. 

Probably not the answer you want but I don’t know what else to say.

**Comment by 0x0c** [comment]
Yes, currently it works, but need to edit SwiftOSC, so it is not convenient when using cocoa pods.
Is it possible to merge my code when I send pull request?

**Comment by devinroth** [comment]
Yeah I’d be willing to do that. The only thing you changed was made the UDPClient public right?

Devin

**Comment by 0x0c** [comment]
Yes, my workaround is that made the UDPClient public.
I think this change is not good for broadcast messages, because it needs to call `client.client.enableBroadcast()` before send a message.
I'll edit another way to make more convenient, after that I'll send pull request.

**Comment by 0x0c** [comment]
I send pull request, plz check it ;)

https://github.com/devinroth/SwiftOSC/pull/33
