### ISSUE TITLE
messages wont transfer? how can we debug?

### ISSUE THREAD

**Issue by Fahad-pnw** [devinroth/SwiftOSC#34]
we've had a simple requirement of triggering commands via the following 3 commands:

    1.) `/hog/playback/go/0/1'
    2.) `/hog/playback/go/0/2'
    3.) `/hog/playback/go/0/3'

i've no idea on how OSC communicates but considering its somewhat a UDP/TCP connection transferring bytedata?

used: https://cocoapods.org/pods/SwiftOSC SwiftOSC library
and simply parsed the messages as following:

    let message = OSCMessage(address, self.message.text!)
    client.send(message)
    let message = OSCMessage(address, "/hog/playback/go/0")
    client.send(message)

further, i could also move to javascript or someother solution that just allows sending data to OSC on an ip/port where the server is.

**Comment by Fahad-pnw** [comment]
so the whole app does one thing, it takes user input for ip and port, connects to the server.
and has 4 buttons to switch the tracks.
i tried looking into the examples but couldn't really find anything that might trigger something on the console. I understand this is not even an "issue" but i really needed to understand better if what we're doing is correct way to do it?

**Comment by devinroth** [comment]
Did you setup the client and send the message?

Do you have the correct IP address/port?

Send me your full code so I can help you better.

**Comment by Fahad-pnw** [comment]
Yes, have set up the client and sent the message.

Did also run an OSC monitor to test it out and the message was successfully received on the monitor, however, since i've no clue on how to assemble a message which the "console" can read so i've to do much hit and try.  I dont know if we have it formatted correctly, we dont have the console and the only requirement was to send out the command "/hog/playback/go/0/1" "/hog/playback/go/0/2" to alter the tracks being played.

i'm sending the code in a minute.

**Comment by Fahad-pnw** [comment]
`//
//  ViewController.swift
//  SoundServer
//
//  Created by renameme on 3/13/19.
//  Copyright © 2019 Penandweb. All rights reserved.
//

import UIKit
import SwiftOSC


class ClientViewController: UIViewController {

    // Setup Client. Change address from localhost if needed.
    var client = OSCClient(address: IPADDRESS, port: PORTNUMBER)
    var address = OSCAddressPattern("/")
    @IBOutlet var port: UITextField!
    @IBOutlet var ipAddress: UITextField!
    @IBOutlet var message: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        ipAddress.text = IPADDRESS
        port.text = "\(PORTNUMBER)"
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    
    @IBAction func connect(_ sender: UITextField) {
        
        if let number = Int(port.text!) {
            client = OSCClient(address: ipAddress.text!, port: number)
        }
    }
    
    @IBAction func sendText(_ sender: UIButton) {
        let message = OSCMessage(address, self.message.text!)
        client.send(message)
    }
    
    @IBAction func button1(_ sender: UIButton) {
        let message = OSCMessage(address, "/hog/playback/go/0")
        client.send(message)
    }
    
    @IBAction func button2(_ sender: UIButton) {
        let message = OSCMessage(address, "/hog/playback/go/1")
        client.send(message)
    }
    
    @IBAction func button3(_ sender: UIButton) {
        let message = OSCMessage(address, "/hog/playback/go/2")
        client.send(message)
    }

}

extension ClientViewController: UITextFieldDelegate {
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }
    
}
`

**Comment by devinroth** [comment]
What exactly are you trying to communicate with? 

Sounds like you have it setup correctly on this end.

**Comment by Fahad-pnw** [comment]
strangely, all i know right now is that its a "console" that control tracks/lights. I'm finding more information on that but only the following details were sent and that "messages" need to be sent on a udp protocol, thought it would be pretty easy but now i'm quite blank on how to begin debugging considering i don't really have a visual feedback. 
Thank you for your help and the support, i'll pass on the details of the device as soon as i find more and seek your help further later today or tomorrow! 
https://www.highend.com/pub/support/controllers/documents/HTML/en/sect-osc_mappings.htm

**Comment by Fahad-pnw** [comment]
okay, so the data was successfully sent.
thanks on that:
here's what's happening...some formatting issue, if you have an idea on that:

https://ibb.co/jrcZ04K
https://ibb.co/N9CgrdK

**Comment by devinroth** [comment]
Okay so I see what’s happening. You’re sending nothing to the address and it is expecting an int. 

Try 

let message = OSCMessage(address, "/hog/playback/go/0", 0) 
client.send(message)

Devin

**Comment by SammyTheHand** [comment]
Coincidentally I work for the manufacturer of the hog console that you are attempting to communicate with and have an interest in OSC so have been following this framework, so you luckily have found the right person to talk to... 
I should firstly suggest reading the online manual here  <https://www.highend.com/pub/support/controllers/documents/HTML/en/sect-osc_intro.htm>
To Go a specific cue in a list (goto) you need to send "/hog/playback/go/0” with (oddly) a string argument “1.1”.

Using comma equals annotation:
/hog/playback/go/0=<cue list number>.<cue number>

Apologise the manual doesn’t clearly state the argument data type you need to send.

**Comment by devinroth** [comment]
So using SwiftOSC you would use:

let message = OSCMessage(address, "/hog/playback/go/0", “1.1”)

Correct? 

Devin

**Comment by Fahad-pnw** [comment]
@SammyTheHand my lucky day to have received support in such quick fashion!
@devinroth Thanks, will test and confirm here asap!

thanks again you both!

**Comment by Fahad-pnw** [comment]
for now its sending:
Button 1: `/hog/playback/go/0 1.1` (missing the `/` and has an extra space
instead of 
Button 1: `/hog/playback/go/0/1.1`

with touchOSC it sends as a single string without any space and a /, which works..
still debugging.
