### ISSUE TITLE
using SwiftOSC in Objective C audio unit

### ISSUE THREAD

**Issue by scottawardle** [devinroth/SwiftOSC#35]
Really enjoying using SwiftOSC in a simple swift app on iOS, but I'd also really like to be able to use it in an Audio Unit project I've already got with a ton of Objective-C++ legacy code which I can't afford to rewrite as Swift.  Can someone tell me how or if it's possible to use SwiftOSC in an Objective-C++ project?

Thanks in advance.

**Comment by devinroth** [comment]
I know Obj C libraries work in Swift but I don’t know if it works the other way around. I’ll try it out and let you know.

**Comment by devinroth** [comment]
Doesn’t look like it works. From what I read there is a way to open up Swift libraries and functions to ObjC with the @objc attribute makes it visible to ObjC. 

Unfortunately I don’t code in ObjC so I have no desire to support it. You could fork SwiftOSC and see if you can get it working in ObjC.

Devin
