### ISSUE TITLE
Using all of the memory

### ISSUE THREAD

**Issue by ADE222070** [devinroth/SwiftOSC#36]
Hi there, I have added SwiftOSC into my project, I'm currently sending 18 (just to speed up the process) constant OSC streams to it and the memory just keeps climbing. It will get to 1.37GB and crash the app.

When I pause the OSC streams and stop sending to it, the memory flat lines.

Your help would be highly appreciated.

**Comment by devinroth** [comment]
Sounds like a memory leak if I’ve ever heard of one. I’ll take a look.

**Comment by ADE222070** [comment]
Yeah I've been doing research into it but can't get my head around where to start. That would be amazing. Thank you

**Comment by devinroth** [comment]
This is on the server side right? When receiving data. 

I’ll track it down when I get a chance.

**Comment by ADE222070** [comment]
Yes it's the server side. Thanks

**Comment by devinroth** [comment]
Okay I did an initial check. Looks like there are some minor leaks but nothing causing what you describe. I tossed a ton of data at it but it only ever takes up 60-70 mb and then a crash. I’ll try to track it down.

**Comment by ADE222070** [comment]
Thanks for doing some initial testing. I've just made a quick video showing my results in the hope it helps you. Just click the image below to have a look on YouTube.

[![OSC Memory Leak Test Video ](https://img.youtube.com/vi/CZnQsnZMLeg/0.jpg)](https://www.youtube.com/watch?v=CZnQsnZMLeg)

I was sending the OSC from a program called Isadora. [Here](https://mega.nz/#!wCJUVYzJ!ifaCUUs1Sxmd3WxEijvsjhgjbmXz5T7GEwfbMJuwRQs) is a link to my Isadora patch if you would like to test with it too. 
Isadora can be download from [here](https://troikatronix.com/get-it/) and comes with a free trial that allows you to use all features other than save.

**Comment by devinroth** [comment]
What’s your code?

**Comment by devinroth** [comment]
This is super helpful. Thanks.

**Comment by ADE222070** [comment]
Hi there, sure my code is available [here](https://github.com/Research-Production-Park/SwiftOSCMemLeak).

If I've done it correctly you should have access to this. It's a mess I know, I'm still very new at this all.

**Comment by devinroth** [comment]
Solved the issue. Some strings were not being released from the pool. Solved the issue by wrapping in autoreleasepool. Just commited changes.

**Comment by ADE222070** [comment]
I'll check this out now. Thanks for a speedy solution. I do have another issue but will post it separably for  future users looking at the issues.

**Comment by ADE222070** [comment]
Apologies just one last thing,
I installed SwiftOSC using pods. How would I go ahead with updating? I've ran pod update but I'm assuming your fix will take a while to appear as a pod update?

(I have no idea if pods are updated from here or if you must publish another update for them)

Thanks

**Comment by devinroth** [comment]
There seems to be some issues update cocoapods. I'll reply once it's done.

**Comment by devinroth** [comment]
Should be up now.

**Comment by ADE222070** [comment]
Thanks, I managed to update to 1.2.7, but unfortunately this did not fix the issue.

Thanks

Aled

**Comment by devinroth** [comment]
It must be something else in your code. I ran your Memory Leak patch and replicated your results, fixed the issue, and even doubled the stream and ran it for 15 minutes with a steady 18.6mb of memory.



My guess is you are retaining the data once received. 

Run my OSCMonitor app and check it.

**Comment by devinroth** [comment]
There are other memory issues that I need to deal with but your app shouldn’t be taking on memory like before. I’ll continue to fix them. 

Devin
