### ISSUE TITLE
unclear how to use bundles

### ISSUE THREAD

**Issue by lysdexic-audio** [devinroth/SwiftOSC#38]
Hi Devin,

Looking at the changelog it seems that timetags in bundles are now supported, I'm not super clear on the syntax for how to send bundles from an IOS client

Any chance of some simple demo code on the Readme?

**Comment by devinroth** [comment]
I just added an example in the playgrounds file. 

Create a message
`var message = OSCMessage(OSCAddressPattern("/test"), 110)'

Add the message to a bundle with a timetag
'var bundle = OSCBundle(Timetag(secondsSinceNow: 5.0), message)`

Send the bundle
'client.send(bundle)'

If the server fully supports timetags, like SwiftOSC, the bundle will be delivered at the correct time.

**Comment by lysdexic-audio** [comment]
Thanks Devin!
