### ISSUE TITLE
Any plans on adding this to CocoaPods?

### ISSUE THREAD

**Issue by j0hnm4r5** [devinroth/SwiftOSC#8]
It would be [pretty easy](https://guides.cocoapods.org/making/making-a-cocoapod.html)! I'm not sure if it would work with a fork/pull request, otherwise I'd do it myself.

**Comment by devinroth** [comment]
Not a bad idea. I can take a look at setting it up sometime next week when I get a chance.

**Comment by lvmelody** [comment]
Up voting this idea...

**Comment by devinroth** [comment]
I've been getting lots request for CocoaPods. Sorry I haven't had a chance to add this yet. Still in the plans.

**Comment by devinroth** [comment]
All setup and running with CocoaPods. 

pod 'SwiftOSC', '~> 1.1'
